<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>de.muenchen.eai</groupId>
  <artifactId>eakte-fscgovxml-java-client</artifactId>
  <version>2.0.1-SNAPSHOT</version>

  <properties>
    <java.version>21</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>

    <!-- needed for compilation, provides package "jakarta.xml.bind.annotation" -->
    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <version>4.0.0</version>
    </dependency>

  </dependencies>

  <build>
    <plugins>

      <!-- recipe from eAS: -->
      <plugin>
        <groupId>org.apache.cxf</groupId>
        <artifactId>cxf-codegen-plugin</artifactId>
        <version>4.2.0</version>  <!-- upgraded from 3.5.7 -->
        <executions>
          <execution>
            <id>generate-sources-faba</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>wsdl2java</goal>
            </goals>
            <configuration>
              <sourceRoot>${project.build.directory}/generated-sources/cxf</sourceRoot>
              <wsdlOptions>

                <wsdlOption>

                  <!-- von Rabis, eAkte26:
                  <wsdl>${project.basedir}/src/main/resources/fscgovxml-10.wsdl</wsdl>
                  -->
                  <!-- aus eAS-Quelltext: -->
                  <wsdl>${project.basedir}/src/main/resources/2026-04-08_eakte26.wsdl</wsdl>

                  <extendedSoapHeaders>true</extendedSoapHeaders>
                  <!-- ,,,fh commented
                  <bindingFiles>
                    <bindingFile>./src/main/resources/2022-binding.xjb</bindingFile>
                  </bindingFiles>
                  <extraargs>
                    <extraarg>
                      -xjc-Xts:style:de.bayern.itdlz.eakte.eas.EasToStringStyle.EAS_TO_STRING_STYLE
                    </extraarg>
                    <extraarg>-xjc-Xfluent-api</extraarg>
                  </extraargs>
                  -->
                </wsdlOption>

              </wsdlOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

</project>
