<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>de.muenchen.eai</groupId>
  <artifactId>eakte-api-v1</artifactId>
  <version>1.2.7-SNAPSHOT</version>
  <packaging>pom</packaging>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/licenses/MIT</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <modules>
    <module>eakte-api-v1-spec</module>
    <module>eakte-api-v1-spec-single-file</module>
    <module>eakte-api-v1-spring-boot-server-stubs</module>
  </modules>

</project>
