/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.controllers;

import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.DefinitionenFuerVerfahrenListeResponse;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import jakarta.servlet.http.HttpServletRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.21.0")
@Validated
@Controller
@Tag(name = "DefinitionenFuerVerfahren", description = "the DefinitionenFuerVerfahren API")
public interface DefinitionenFuerVerfahrenApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_LESE_DEFINITIONEN_FUER_VERFAHREN = "/api/v2/definitionen-fuer-verfahren";
    /**
     * GET /api/v2/definitionen-fuer-verfahren : DfV-Metadaten abrufen
     * Mit diesem Aufruf können die Metadaten con DfVs abgerufen werden. 
     *
     * @param fachverfahrensID **Aufrufende Fachanwendung**  Die FachverfahrensID identifziert ein Fachverfahren behördenunabhängig und wird vom Betrieb eAkte vergeben  Der mitgegebene Wert wird auch als Http-Header in der Antwort zurückgegeben.  Somit ist ein Filtern der Antworten nach Fachverfahren möglich.  (optional)
     * @param loginName **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts  (optional)
     * @param stelle Referenz der Stelle (**Stelle des Nutzers** in der eAkte). * Sachbearbeitung - OfficialInCharge * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Fachadministration - OpAdm * Schriftgutverwaltung - DocumentManager  Es dürfen ausschließlich die Stellen genannt werden,  die bei der LHM genutzt werden.\\ Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @param organisationseinheit URI der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Die OE ist dann wichtig anzugeben,  wenn der Nutzer in mehreren OEs zugeordnet ist.\\ Über diese OE wird der Mandant zugeordnet und  entsprechend die Berechtigungen geprüft.  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "leseDefinitionenFuerVerfahren",
        summary = "DfV-Metadaten abrufen",
        description = "Mit diesem Aufruf können die Metadaten con DfVs abgerufen werden. ",
        tags = { "DefinitionenFuerVerfahren" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DefinitionenFuerVerfahrenListeResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DefinitionenFuerVerfahrenListeResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DefinitionenFuerVerfahrenListeResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DefinitionenFuerVerfahrenListeResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "basicAuth"),
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DefinitionenFuerVerfahrenApi.PATH_LESE_DEFINITIONEN_FUER_VERFAHREN,
        produces = { "application/json" }
    )
    default ResponseEntity<DefinitionenFuerVerfahrenListeResponse> leseDefinitionenFuerVerfahren(
        @Parameter(name = "FachverfahrensID", description = "**Aufrufende Fachanwendung**  Die FachverfahrensID identifziert ein Fachverfahren behördenunabhängig und wird vom Betrieb eAkte vergeben  Der mitgegebene Wert wird auch als Http-Header in der Antwort zurückgegeben.  Somit ist ein Filtern der Antworten nach Fachverfahren möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "FachverfahrensID", required = false) Optional<String> fachverfahrensID,
        @Parameter(name = "Login-Name", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts ", in = ParameterIn.HEADER) @RequestHeader(value = "Login-Name", required = false) Optional<String> loginName,
        @Parameter(name = "Stelle", description = "Referenz der Stelle (**Stelle des Nutzers** in der eAkte). * Sachbearbeitung - OfficialInCharge * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Fachadministration - OpAdm * Schriftgutverwaltung - DocumentManager  Es dürfen ausschließlich die Stellen genannt werden,  die bei der LHM genutzt werden.\\ Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "Stelle", required = false) Optional<String> stelle,
        @Parameter(name = "Organisationseinheit", description = "URI der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Die OE ist dann wichtig anzugeben,  wenn der Nutzer in mehreren OEs zugeordnet ist.\\ Über diese OE wird der Mandant zugeordnet und  entsprechend die Berechtigungen geprüft. ", in = ParameterIn.HEADER) @RequestHeader(value = "Organisationseinheit", required = false) Optional<String> organisationseinheit,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"anzahlDefinitionenFuerVerfahren\" : 3, \"definitionenFuerVerfahrenListe\" : [ { \"istEntwurf\" : false, \"attributURIs\" : [ \"attributURIs\", \"attributURIs\" ], \"eigeneUrl\" : \"/v2/Ressourcen/ressourcenId\", \"name\" : \"Akte\" }, { \"istEntwurf\" : false, \"attributURIs\" : [ \"attributURIs\", \"attributURIs\" ], \"eigeneUrl\" : \"/v2/Ressourcen/ressourcenId\", \"name\" : \"Akte\" } ], \"success\" : true, \"error\" : { \"easDetail\" : \"easDetail\", \"easFehler\" : \"easFehler\", \"easFehlercode\" : 0 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"anzahlDefinitionenFuerVerfahren\" : 3, \"definitionenFuerVerfahrenListe\" : [ { \"istEntwurf\" : false, \"attributURIs\" : [ \"attributURIs\", \"attributURIs\" ], \"eigeneUrl\" : \"/v2/Ressourcen/ressourcenId\", \"name\" : \"Akte\" }, { \"istEntwurf\" : false, \"attributURIs\" : [ \"attributURIs\", \"attributURIs\" ], \"eigeneUrl\" : \"/v2/Ressourcen/ressourcenId\", \"name\" : \"Akte\" } ], \"success\" : true, \"error\" : { \"easDetail\" : \"easDetail\", \"easFehler\" : \"easFehler\", \"easFehlercode\" : 0 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"anzahlDefinitionenFuerVerfahren\" : 3, \"definitionenFuerVerfahrenListe\" : [ { \"istEntwurf\" : false, \"attributURIs\" : [ \"attributURIs\", \"attributURIs\" ], \"eigeneUrl\" : \"/v2/Ressourcen/ressourcenId\", \"name\" : \"Akte\" }, { \"istEntwurf\" : false, \"attributURIs\" : [ \"attributURIs\", \"attributURIs\" ], \"eigeneUrl\" : \"/v2/Ressourcen/ressourcenId\", \"name\" : \"Akte\" } ], \"success\" : true, \"error\" : { \"easDetail\" : \"easDetail\", \"easFehler\" : \"easFehler\", \"easFehlercode\" : 0 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"anzahlDefinitionenFuerVerfahren\" : 3, \"definitionenFuerVerfahrenListe\" : [ { \"istEntwurf\" : false, \"attributURIs\" : [ \"attributURIs\", \"attributURIs\" ], \"eigeneUrl\" : \"/v2/Ressourcen/ressourcenId\", \"name\" : \"Akte\" }, { \"istEntwurf\" : false, \"attributURIs\" : [ \"attributURIs\", \"attributURIs\" ], \"eigeneUrl\" : \"/v2/Ressourcen/ressourcenId\", \"name\" : \"Akte\" } ], \"success\" : true, \"error\" : { \"easDetail\" : \"easDetail\", \"easFehler\" : \"easFehler\", \"easFehlercode\" : 0 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
