openapi: 3.0.1

info:
  title: eAkte REST-API Spezifikation
  description: Spezifikation für die REST-Schnittstelle der eAkte
  version: '2.0.0'

  contact:
    name: Competence Center eAkte
    url: https://it-at-m.github.io/eakte-schnittstelle
    email: schnittstelle.eakte@muenchen.de

  license:
    name: MIT
    url: https://github.com/it-at-m/eakte-schnittstelle/blob/main/LICENSE

servers:
  - url: http://localhost:8080

components:
  securitySchemes:
    bearerAuth:
      $ref: '_SicherheitsSchemata.yaml#/components/securitySchemes/bearerAuth'

security:
  - bearerAuth: []

paths:
  '/api/v2/vorgaenge':
    $ref: 'Vorgaenge.yaml'
