spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://sso.muenchen.de/auth/realms/muenchen.de/protocol/openid-connect/certs
  web:
    resources:
      static-locations: "classpath:/static/,file:/opt/myapp/static/"

logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.springframework.boot: WARN
    org.apache.cxf: WARN
    de.muenchen.itm.eakte.schnittstelle: INFO
    de.muenchen.itm.eakte.schnittstelle.web.helper.de.muenchen.itm.eakte.schnittstelle.adapter.web.helper.EndpointDescriptor: INFO
  pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %80.80logger - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %-80.80logger - %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    url: /openapi/eakte-rest-api-v2/__ServiceDefinition.yaml
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  paths-to-match: /**

eakte-connection-parameter:
  eGovServiceAddress: "https://eakte26-k2-authldap.muenchen.de"
  # BAY: "http://eakte-easint.rz-egov.bybn.de"
  eGovServicePath: "/fsc/fscdav/wsdl?WEBSVC=FSCGOVXML_1_1001_DefaultWebServiceDefinition"
  # BAY: "/fsc/fscdav/wsdl?websvc=FSCGOVXML@1.1001:DefaultWebServiceDefinition"

app-configuration:
  attributbeschreibungen:

    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "COOSYSTEM@1.1:objname"
      bezeichnung: "Objektname"
      beschreibung: "BESCHREIBUNG NACHTRAGEN!"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-objname"

    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "COOSYSTEM@1.1:objaddress"
      bezeichnung: "Objektadresse"
      beschreibung: "BESCHREIBUNG NACHTRAGEN!"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-objaddress"

    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "COOELAK@1.1001:objmlname"
      bezeichnung: "Objektname Mehrsprachig"
      beschreibung: "BESCHREIBUNG NACHTRAGEN!"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-objmlname"

    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "COOELAK@1.1001:fileouobj"
      bezeichnung: "Aktenführende Organisationseinheit"
      beschreibung: "BESCHREIBUNG NACHTRAGEN!"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-fileouobj"

    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "COOELAK@1.1001:filesubj"
      bezeichnung: "Betreff : mehrzeilig)"
      beschreibung: "BESCHREIBUNG NACHTRAGEN!"
      datentyp: ZEICHENKETTE          
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-filesubj"
    
    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "FSCFOLIO@1.1001:objaccdef"
      bezeichnung: "Zugriffsdefinition"
      beschreibung: "BESCHREIBUNG NACHTRAGEN!"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-objaccdef"


    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "CFGBAYERN@15.1400:procedureaccessdefinition"
      bezeichnung: "Zugriffsdefinition für Vorgänge"
      beschreibung: "BESCHREIBUNG NACHTRAGEN!"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-procedureaccessdefinition"


    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "FSCTERM@1.1001:objterms"
      bezeichnung: "Schlagworte"
      beschreibung: "Angabe der Schlagworte getrennt mit ';'."
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-objterms"
    
    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "COOSYSTEM@1.1:objvalidfrom"
      bezeichnung: "Gültig von"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-objvalidfrom"
    
    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "COOSYSTEM@1.1:objvalidto"
      bezeichnung: "Gültig bis"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-objvalidto"

    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "COOSYSTEM@1.1:objowner"
      bezeichnung: "Eigentuemer"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/Akte-objowner"
    
    - referenzSchriftgutObjektklasseOderFormular: "DEPRECONFIG@15.1001:SubjectAreaFile"
      referenzAttribut: "lhmdfvpublic@2150.8800:fh_attr_auf_Formularebene"
      bezeichnung: "Attribut auf Aktenebene"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/lhmdfvpublic-fh_attr_auf_Formularebene"
    
    - referenzSchriftgutObjektklasseOderFormular: "lhmdfvpublic"
      referenzAttribut: "lhmdfvpublic@2150.8800:fhattr1"
      bezeichnung: "MyAttr1"
      datentyp: ZEICHENKETTE
      pflichtFeld: false
      maximaleTextLaenge: 64
      eigeneUrl: "/Attributbeschreibungen/lhmdfvpublic-fhattr1"

  funktions-username: USER

  funktions-password: PASSWD

  attributeCacheMaxTimeToLiveInSeconds: 300