package de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.springframework.lang.Nullable;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;

/**
 * AttributUriUndWert
 */

@JsonIgnoreProperties(
  value = "datenTyp", // ignore manually set datenTyp, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the datenTyp to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "datenTyp", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = AttributAggregatstyp.class, name = "Aggregatstyp"),
  @JsonSubTypes.Type(value = AttributAktenURI.class, name = "AktenURI"),
  @JsonSubTypes.Type(value = AttributAktenplaneintragsURI.class, name = "AktenplaneintragsURI"),
  @JsonSubTypes.Type(value = AttributAufzaehlungstyp.class, name = "Aufzaehlungstyp"),
  @JsonSubTypes.Type(value = AttributBase64EncodedContent.class, name = "Base64EncodedContent"),
  @JsonSubTypes.Type(value = AttributBenutzerURI.class, name = "BenutzerURI"),
  @JsonSubTypes.Type(value = AttributBoolescherWert.class, name = "BoolescherWert"),
  @JsonSubTypes.Type(value = AttributDatum.class, name = "Datum"),
  @JsonSubTypes.Type(value = AttributDatumMitUhrzeit.class, name = "DatumMitUhrzeit"),
  @JsonSubTypes.Type(value = AttributDokumentURI.class, name = "DokumentURI"),
  @JsonSubTypes.Type(value = AttributFliesskommazahl.class, name = "Fliesskommazahl"),
  @JsonSubTypes.Type(value = AttributGanzzahl.class, name = "Ganzzahl"),
  @JsonSubTypes.Type(value = AttributOrganisationseinheitsURI.class, name = "OrganisationseinheitsURI"),
  @JsonSubTypes.Type(value = AttributSchriftstueckURI.class, name = "SchriftstueckURI"),
  @JsonSubTypes.Type(value = AttributSprachenURI.class, name = "SprachenURI"),
  @JsonSubTypes.Type(value = AttributUnspezifischeRessourcenURI.class, name = "UnspezifischeRessourcenURI"),
  @JsonSubTypes.Type(value = AttributVorgangsURI.class, name = "VorgangsURI"),
  @JsonSubTypes.Type(value = AttributZeichenkette.class, name = "Zeichenkette"),
  @JsonSubTypes.Type(value = AttributZugriffsdefinitionsURI.class, name = "ZugriffsdefinitionsURI")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.21.0")
public class AttributUriUndWert {

  private String attributURI;

  private String datenTyp;

  public AttributUriUndWert() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public AttributUriUndWert(String attributURI, String datenTyp) {
    this.attributURI = attributURI;
    this.datenTyp = datenTyp;
  }

  public AttributUriUndWert attributURI(String attributURI) {
    this.attributURI = attributURI;
    return this;
  }

  /**
   * Get attributURI
   * @return attributURI
   */
  @NotNull 
  @Schema(name = "attributURI", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("attributURI")
  public String getAttributURI() {
    return attributURI;
  }

  @JsonProperty("attributURI")
  public void setAttributURI(String attributURI) {
    this.attributURI = attributURI;
  }

  public AttributUriUndWert datenTyp(String datenTyp) {
    this.datenTyp = datenTyp;
    return this;
  }

  /**
   * Get datenTyp
   * @return datenTyp
   */
  @NotNull 
  @Schema(name = "datenTyp", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("datenTyp")
  public String getDatenTyp() {
    return datenTyp;
  }

  @JsonProperty("datenTyp")
  public void setDatenTyp(String datenTyp) {
    this.datenTyp = datenTyp;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributUriUndWert attributUriUndWert = (AttributUriUndWert) o;
    return Objects.equals(this.attributURI, attributUriUndWert.attributURI) &&
        Objects.equals(this.datenTyp, attributUriUndWert.datenTyp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributURI, datenTyp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributUriUndWert {\n");
    sb.append("    attributURI: ").append(toIndentedString(attributURI)).append("\n");
    sb.append("    datenTyp: ").append(toIndentedString(datenTyp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

