/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.controllers;

import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.CreateCompleteFileBodyParams;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.CreateCompleteFileResponseDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.CreateFileDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.DmsErrorResponse;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.DmsObjektResponse;
import org.springframework.lang.Nullable;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.ReadFileResponseDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.SearchFileRequestDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.SearchFileResponseDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.UpdateFileDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import jakarta.servlet.http.HttpServletRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.21.0")
@Validated
@Controller
@Tag(name = "/files", description = "the /files API")
public interface FilesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_COMPLETE_FILE = "/files/complete";
    /**
     * POST /files/complete : Anlegen einer kompletten Akte mit Vorgängen, Dokumenten und Schriftstücken
     * Es wird eine komplette Sachakte erstellt mit einem Vorgang, Dokument &amp; Schrifstück) bzw. man kann auch einzelne Schriftstücke bei der Akte ergänzen.&lt;br&gt; Bitte beachten Sie die Bedingungen beim Anlegen von einfachen Akten (POST /files)
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)&lt;br&gt; Log-in-Name des Benutzerobjekts  (required)
     * @param params  (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.&lt;br&gt; &lt;br&gt; Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.&lt;br&gt; Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.&lt;br&gt; Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.&lt;br&gt; Hinweis:&lt;br&gt; Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.&lt;br&gt; Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @param giattachmenttype Liste der Objektadressen und Namen der Schriftstücke im Dokument (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "createCompleteFile",
        summary = "Anlegen einer kompletten Akte mit Vorgängen, Dokumenten und Schriftstücken",
        description = "Es wird eine komplette Sachakte erstellt mit einem Vorgang, Dokument & Schrifstück) bzw. man kann auch einzelne Schriftstücke bei der Akte ergänzen.<br> Bitte beachten Sie die Bedingungen beim Anlegen von einfachen Akten (POST /files)",
        tags = { "/files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateCompleteFileResponseDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = FilesApi.PATH_CREATE_COMPLETE_FILE,
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<CreateCompleteFileResponseDTO> createCompleteFile(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)<br> Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "params", description = "", required = true) @Valid @RequestPart(value = "params", required = true) CreateCompleteFileBodyParams params,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.<br> <br> Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.<br> Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.<br> Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.<br> Hinweis:<br> Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.<br> Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(name = "giattachmenttype", description = "Liste der Objektadressen und Namen der Schriftstücke im Dokument") @RequestPart(value = "giattachmenttype", required = false) List<MultipartFile> giattachmenttype,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"objnameprocedure\" : \"0010 A20 011-2016 Anträge Firma XY-4\", \"objnamedocument\" : \"0010 A20 011-2016 Anträge Firma XY-4\", \"objidprocedure\" : \"COO.1.2301.1.1042406\", \"objnamefile\" : \"0010 A20 011-2016 Anträge Firma XY-4\", \"objiddocument\" : \"COO.1.2301.1.1042406\", \"objnamecontent\" : \"0010 A20 011-2016 Anträge Firma XY-4\", \"objidcontent\" : \"COO.1.2301.1.1042406\", \"objidfile\" : \"COO.1.2301.1.1042406\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_FILE = "/files";
    /**
     * POST /files : Akte anlegen
     * Sachakten können nur in Aktenplaneinträgen des Aktenplaneintragstyps „Betreffseinheit“ angelegt werden,  d.h. auf der untersten Ebene eines Aktenplans.      Ist der übergebene Aktenplaneintrag eine Betreffseinheit (unterstes Element im Aktenplan),  prüft das System, ob die Betreffseinheit noch frei ist (weniger als 10.000 Akten in der Betreffseinheit) * Ist die Betreffseinheit frei, wird die Akte in der Betreffseinheit abgelegt. * Ist die Betreffseinheit nicht frei, prüft das System, ob bereits weitere Betreffseinheiten angelegt wurden und ob diese frei sind. * Ist eine andere bereits angelegte Betreffseinheit frei, wird die Akte in dieser Betreffseinheit abgelegt * Wurde noch keine weitere Betreffseinheit angelegt oder sind alle automatisch angelegten voll,  wird eine neue Betreffseinheit auf der gleichen Ebene mit folgendem Namen angelegt: Aktenplanzeichen: &lt;Name des darüberliegenden Aktenplaneintrags&gt; + „.„ + &lt;Fortlaufende Nummer&gt;\\  Die Akte wird in der neu erzeugten Betreffseinheit angelegt.  Ist der übergebene Aktenplaneintrag keine Betreffseinheit,  eruiert das System die Liste der Betreffseinheiten, welche eine Ebene tiefer sind.&lt;br&gt; Das System prüft, ob eine dieser Betreffseinheiten frei ist. * Wenn eine freie Betreffseinheit gefunden wird, wird die Akte in der freien Betreffseinheit angelegt. * Wenn keine freie Betreffseinheit gefunden wird, wird eine neue Betreffseinheit unterhalb des übergebenen Aktenplaneintrages mit folgendem Namen angelegt:&lt;br&gt; „Name des darüberliegenden Aktenplaneintrags„ + „.„ + „Fortlaufende Nummer„&lt;br&gt; Die Akte wird in der neu erzeugten Betreffseinheit erzeugt.  Als Organisationseinheit der Sachakte (COOSYSTEM@1.1:objowngroup) wird  die Organisationseinheit des darüber liegenden Aktenplankennzeichens (COOELAK@1.1001:ou) gesetzt.  Sofern keine Organisationseinheit auf dem Aktenplankennzeichen definiert ist,  wird die Organisationseinheit der ersten Rolle des Benutzers verwendet. 
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)&lt;br&gt; Log-in-Name des Benutzerobjekts  (required)
     * @param createFileDTO  (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.&lt;br&gt; &lt;br&gt; Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.&lt;br&gt; Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.&lt;br&gt; Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.&lt;br&gt; Hinweis:&lt;br&gt; Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.&lt;br&gt; Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "createFile",
        summary = "Akte anlegen",
        description = "Sachakten können nur in Aktenplaneinträgen des Aktenplaneintragstyps „Betreffseinheit“ angelegt werden,  d.h. auf der untersten Ebene eines Aktenplans.      Ist der übergebene Aktenplaneintrag eine Betreffseinheit (unterstes Element im Aktenplan),  prüft das System, ob die Betreffseinheit noch frei ist (weniger als 10.000 Akten in der Betreffseinheit) * Ist die Betreffseinheit frei, wird die Akte in der Betreffseinheit abgelegt. * Ist die Betreffseinheit nicht frei, prüft das System, ob bereits weitere Betreffseinheiten angelegt wurden und ob diese frei sind. * Ist eine andere bereits angelegte Betreffseinheit frei, wird die Akte in dieser Betreffseinheit abgelegt * Wurde noch keine weitere Betreffseinheit angelegt oder sind alle automatisch angelegten voll,  wird eine neue Betreffseinheit auf der gleichen Ebene mit folgendem Namen angelegt: Aktenplanzeichen: <Name des darüberliegenden Aktenplaneintrags> + „.„ + <Fortlaufende Nummer>\\  Die Akte wird in der neu erzeugten Betreffseinheit angelegt.  Ist der übergebene Aktenplaneintrag keine Betreffseinheit,  eruiert das System die Liste der Betreffseinheiten, welche eine Ebene tiefer sind.<br> Das System prüft, ob eine dieser Betreffseinheiten frei ist. * Wenn eine freie Betreffseinheit gefunden wird, wird die Akte in der freien Betreffseinheit angelegt. * Wenn keine freie Betreffseinheit gefunden wird, wird eine neue Betreffseinheit unterhalb des übergebenen Aktenplaneintrages mit folgendem Namen angelegt:<br> „Name des darüberliegenden Aktenplaneintrags„ + „.„ + „Fortlaufende Nummer„<br> Die Akte wird in der neu erzeugten Betreffseinheit erzeugt.  Als Organisationseinheit der Sachakte (COOSYSTEM@1.1:objowngroup) wird  die Organisationseinheit des darüber liegenden Aktenplankennzeichens (COOELAK@1.1001:ou) gesetzt.  Sofern keine Organisationseinheit auf dem Aktenplankennzeichen definiert ist,  wird die Organisationseinheit der ersten Rolle des Benutzers verwendet. ",
        tags = { "/files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsObjektResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = FilesApi.PATH_CREATE_FILE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<DmsObjektResponse> createFile(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)<br> Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "CreateFileDTO", description = "", required = true) @Valid @RequestBody CreateFileDTO createFileDTO,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.<br> <br> Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.<br> Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.<br> Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.<br> Hinweis:<br> Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.<br> Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"objname\" : \"objname\", \"objid\" : \"objid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_READ_FILE = "/files/{objaddress}";
    /**
     * GET /files/{objaddress} : Akte lesen
     * Ausgabe der jeweiligen Metadaten der übergebenen Sachakte.&lt;br&gt; Stornierte Objekte können nicht ausgelesen werden.  D.h. Objekte mit dem Status „Storniert“ [FSCFOLIO@1.1001:objdocstate&#x3D;Storniert]  werden gefiltert und nicht zurückgegeben. 
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)&lt;br&gt; Log-in-Name des Benutzerobjekts  (required)
     * @param objaddress Objekt-ID (COO-Adresse) des Objekts (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.&lt;br&gt; &lt;br&gt; Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.&lt;br&gt; Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.&lt;br&gt; Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.&lt;br&gt; Hinweis:&lt;br&gt; Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.&lt;br&gt; Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "readFile",
        summary = "Akte lesen",
        description = "Ausgabe der jeweiligen Metadaten der übergebenen Sachakte.<br> Stornierte Objekte können nicht ausgelesen werden.  D.h. Objekte mit dem Status „Storniert“ [FSCFOLIO@1.1001:objdocstate=Storniert]  werden gefiltert und nicht zurückgegeben. ",
        tags = { "/files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ReadFileResponseDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = FilesApi.PATH_READ_FILE,
        produces = { "application/json" }
    )
    default ResponseEntity<ReadFileResponseDTO> readFile(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)<br> Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "objaddress", description = "Objekt-ID (COO-Adresse) des Objekts", required = true, in = ParameterIn.PATH) @PathVariable("objaddress") String objaddress,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.<br> <br> Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.<br> Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.<br> Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.<br> Hinweis:<br> Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.<br> Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"filesubj\" : \"Alle Anträge der Firma XY aus dem Jahr 2016\", \"fileruntimefrom\" : \"2017-01-13T17:09:42.411+01:00\", \"accdef\" : \"Eigener Mandant\", \"objname\" : \"0010 A20 011-2016 Anträge Firma XY-4\", \"giobjecttype\" : [ { \"name\" : \"Beispielname\", \"id\" : \"COO.2150.9151.1.1206000\" } ], \"fileouobj\" : \"COO.1.2300.1.847\", \"objterms\" : \"Firma XY; Anträge; Anträge 2016\", \"fileruntimetill\" : \"2017-01-13T17:09:42.411+01:00\", \"shortname\" : \"2016 Anträge Firma XY\", \"apentry\" : \"COO.1.2301.1.683\", \"procedureaccdef\" : \"Aktengebunden\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SEARCH_FILE = "/files/search";
    /**
     * POST /files/search : Suche nach Akten über definierte Parameter
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)&lt;br&gt; Log-in-Name des Benutzerobjekts  (required)
     * @param searchFileRequestDTO  (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.&lt;br&gt; &lt;br&gt; Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.&lt;br&gt; Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.&lt;br&gt; Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.&lt;br&gt; Hinweis:&lt;br&gt; Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.&lt;br&gt; Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "searchFile",
        summary = "Suche nach Akten über definierte Parameter",
        tags = { "/files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SearchFileResponseDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = FilesApi.PATH_SEARCH_FILE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SearchFileResponseDTO> searchFile(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)<br> Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "SearchFileRequestDTO", description = "", required = true) @Valid @RequestBody SearchFileRequestDTO searchFileRequestDTO,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.<br> <br> Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.<br> Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.<br> Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.<br> Hinweis:<br> Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.<br> Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"giobjecttype\" : [ { \"objname\" : \"Beispielname\", \"objaddress\" : \"COO.2150.9151.1.1206000\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_FILE = "/files/{objaddress}";
    /**
     * PUT /files/{objaddress} : Akte ändern
     * Bereits befüllte Eigenschaften werden mit übergebenen Werten überschrieben.  Bei keiner Übergabe bleiben die bestehenden Werte erhalten. Bei jeder Änderung über die Schnittstelle wird in der eGov-Suite eine neue Version des Objekts erzeugt. 
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)&lt;br&gt; Log-in-Name des Benutzerobjekts  (required)
     * @param objaddress Objekt-ID (COO-Adresse) des Objekts (required)
     * @param updateFileDTO  (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.&lt;br&gt; &lt;br&gt; Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.&lt;br&gt; Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.&lt;br&gt; Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.&lt;br&gt; Hinweis:&lt;br&gt; Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.&lt;br&gt; Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "updateFile",
        summary = "Akte ändern",
        description = "Bereits befüllte Eigenschaften werden mit übergebenen Werten überschrieben.  Bei keiner Übergabe bleiben die bestehenden Werte erhalten. Bei jeder Änderung über die Schnittstelle wird in der eGov-Suite eine neue Version des Objekts erzeugt. ",
        tags = { "/files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsObjektResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = FilesApi.PATH_UPDATE_FILE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<DmsObjektResponse> updateFile(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)<br> Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "objaddress", description = "Objekt-ID (COO-Adresse) des Objekts", required = true, in = ParameterIn.PATH) @PathVariable("objaddress") String objaddress,
        @Parameter(name = "UpdateFileDTO", description = "", required = true) @Valid @RequestBody UpdateFileDTO updateFileDTO,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.<br> <br> Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.<br> Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.<br> Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.<br> Hinweis:<br> Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.<br> Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"objname\" : \"objname\", \"objid\" : \"objid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
