/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.controllers;

import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.CreateCompleteProcedureBodyParams;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.CreateCompleteProcedureResponseDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.CreateProcedureDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.DmsErrorResponse;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.DmsObjektResponse;
import org.springframework.lang.Nullable;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.ReadProcedureResponseDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.SearchProcedureRequestDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.SearchProcedureResponseDTO;
import de.muenchen.itm.eakte.schnittstelle.rest_v2.server_stubs.model.UpdateProcedureDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import jakarta.servlet.http.HttpServletRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.21.0")
@Validated
@Controller
@Tag(name = "/procedures", description = "the /procedures API")
public interface ProceduresApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_COMPLETE_PROCEDURE = "/procedures/complete";
    /**
     * POST /procedures/complete : Anlegen eines kompletten Vorgangs inkl. Dokument und Schriftstücke
     * Es wird ein kompletter Vorgang mit einem Dokument und Schrifstück neu angelegt  bzw. es können auch einzelne Schriftstücke beim Vorgang ergänzt werden.\\ Sobald eine Sachakte lokalisiert wurde, wird folgendermaßen vorgegangen:  Eingangsparameter Vorgangstitel shortnameprocedure:\\ Das System überprüft ob in der lokalisierten Akte bereits ein Vorgang mit dem Titel existiert. * Vorgang existiert bereits    - Navigieren in den Vorgang * Vorgang existiert noch nicht    - Ein neuer Vorgang mit dem übergebenen Titel wird angelegt und in den Vorgang navigiert.  Eingangsparameter Dokumenttitel shortnamedocument\\ Das System überprüft, ob in dem lokalisierten Vorgang bereits  ein Eingangsdokument mit dem Titel existiert. * Eingangsdokument existiert bereits    - Navigieren in das Eingangsdokument * Eingangsdokument existiert noch nicht    - ein neues Eingangsdokument mit dem übergebenen Titel wird angelegt und in das Eingangsdokument navigiert. 
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts  (required)
     * @param params  (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @param giattachmenttype Liste der Objektadressen und Namen der Schriftstücke im Dokument. (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "createCompleteProcedure",
        summary = "Anlegen eines kompletten Vorgangs inkl. Dokument und Schriftstücke",
        description = "Es wird ein kompletter Vorgang mit einem Dokument und Schrifstück neu angelegt  bzw. es können auch einzelne Schriftstücke beim Vorgang ergänzt werden.\\ Sobald eine Sachakte lokalisiert wurde, wird folgendermaßen vorgegangen:  Eingangsparameter Vorgangstitel shortnameprocedure:\\ Das System überprüft ob in der lokalisierten Akte bereits ein Vorgang mit dem Titel existiert. * Vorgang existiert bereits    - Navigieren in den Vorgang * Vorgang existiert noch nicht    - Ein neuer Vorgang mit dem übergebenen Titel wird angelegt und in den Vorgang navigiert.  Eingangsparameter Dokumenttitel shortnamedocument\\ Das System überprüft, ob in dem lokalisierten Vorgang bereits  ein Eingangsdokument mit dem Titel existiert. * Eingangsdokument existiert bereits    - Navigieren in das Eingangsdokument * Eingangsdokument existiert noch nicht    - ein neues Eingangsdokument mit dem übergebenen Titel wird angelegt und in das Eingangsdokument navigiert. ",
        tags = { "/procedures" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateCompleteProcedureResponseDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProceduresApi.PATH_CREATE_COMPLETE_PROCEDURE,
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<CreateCompleteProcedureResponseDTO> createCompleteProcedure(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "params", description = "", required = true) @Valid @RequestPart(value = "params", required = true) CreateCompleteProcedureBodyParams params,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(name = "giattachmenttype", description = "Liste der Objektadressen und Namen der Schriftstücke im Dokument.") @RequestPart(value = "giattachmenttype", required = false) List<MultipartFile> giattachmenttype,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"objnameprocedure\" : \"0010 A20 011-2016 Anträge Firma XY-4\", \"objnamedocument\" : \"0010 A20 011-2016 Anträge Firma XY-4\", \"objidprocedure\" : \"COO.1.2301.1.1042406\", \"objiddocument\" : \"COO.1.2301.1.1042406\", \"objnamecontent\" : \"0010 A20 011-2016 Anträge Firma XY-4\", \"objidcontent\" : \"COO.1.2301.1.1042406\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_PROCEDURE = "/procedures";
    /**
     * POST /procedures : Vorgang anlegen
     * Unter der angegebenen Akte wird ein neuer Vorgang (ohne Laufweg) angelegt.\\ Für neue Vorgängen wird die auf der Sachakte angegebene Zugriffsdefinition verwendet. 
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts  (required)
     * @param createProcedureDTO  (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "createProcedure",
        summary = "Vorgang anlegen",
        description = "Unter der angegebenen Akte wird ein neuer Vorgang (ohne Laufweg) angelegt.\\ Für neue Vorgängen wird die auf der Sachakte angegebene Zugriffsdefinition verwendet. ",
        tags = { "/procedures" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsObjektResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProceduresApi.PATH_CREATE_PROCEDURE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<DmsObjektResponse> createProcedure(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "CreateProcedureDTO", description = "", required = true) @Valid @RequestBody CreateProcedureDTO createProcedureDTO,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"objname\" : \"objname\", \"objid\" : \"objid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_READ_PROCEDURE = "/procedures/{objaddress}";
    /**
     * GET /procedures/{objaddress} : Vorgang lesen
     * Stornierte Objekte können nicht ausgelesen werden. D.h. Objekte mit dem Status „Storniert“ [FSCFOLIO@1.1001:objdocstate&#x3D;Storniert] werden gefiltert und nicht zurückgegeben.
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts  (required)
     * @param objaddress Objekt-ID (COO-Adresse) des Objekts (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "readProcedure",
        summary = "Vorgang lesen",
        description = "Stornierte Objekte können nicht ausgelesen werden. D.h. Objekte mit dem Status „Storniert“ [FSCFOLIO@1.1001:objdocstate=Storniert] werden gefiltert und nicht zurückgegeben.",
        tags = { "/procedures" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ReadProcedureResponseDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProceduresApi.PATH_READ_PROCEDURE,
        produces = { "application/json" }
    )
    default ResponseEntity<ReadProcedureResponseDTO> readProcedure(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "objaddress", description = "Objekt-ID (COO-Adresse) des Objekts", required = true, in = ParameterIn.PATH) @PathVariable("objaddress") String objaddress,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fileruntimefrom\" : \"2017-01-13T17:09:42.411+01:00\", \"filetype\" : \"Elektronisch\", \"accdef\" : \"Eigener Mandant\", \"procremark\" : \"Warte auf Rückmeldung\", \"objterms\" : \"Firma XY; Anträge; Anträge 2016\", \"objowngroup\" : \"SG A1 0001 (Sachgebiet A1 0001)\", \"shortname\" : \"2016 Anträge Firma XY\", \"filesubj\" : \"Alle Anträge der Firma XY aus dem Jahr 2016\", \"objdocstate\" : \"In Bearbeitung\", \"bostate\" : \"Erstellt\", \"objname\" : \"Anfrage Baugenehmigung (0010 A20 011-4-0006)\", \"giobjecttype\" : [ { \"name\" : \"Beispielname\", \"id\" : \"COO.2150.9151.1.1206000\" } ], \"fileruntimetill\" : \"2017-01-13T17:09:42.411+01:00\", \"referrednumber\" : \"COO.1.2301.1.1042406\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SEARCH_PROCEDURE = "/procedures/search";
    /**
     * POST /procedures/search : Suche nach Vorgängen über definierte Parameter
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts  (required)
     * @param searchProcedureRequestDTO  (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "searchProcedure",
        summary = "Suche nach Vorgängen über definierte Parameter",
        tags = { "/procedures" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SearchProcedureResponseDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProceduresApi.PATH_SEARCH_PROCEDURE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SearchProcedureResponseDTO> searchProcedure(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "SearchProcedureRequestDTO", description = "", required = true) @Valid @RequestBody SearchProcedureRequestDTO searchProcedureRequestDTO,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"giobjecttype\" : [ { \"objname\" : \"Beispielname\", \"objaddress\" : \"COO.2150.9151.1.1206000\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_PROCEDURE = "/procedures/{objaddress}";
    /**
     * PUT /procedures/{objaddress} : Vorgang ändern
     * Bereits befüllte Eigenschaften werden mit der übergebenen Eingabe überschrieben. Bei keiner Übergabe bleiben die bestehenden Werte erhalten. Bei jeder Änderung über die Schnittstelle wird in der eGov-Suite eine neue Version des Objekts erzeugt.
     *
     * @param userlogin **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts  (required)
     * @param objaddress Objekt-ID (COO-Adresse) des Objekts (required)
     * @param updateProcedureDTO  (required)
     * @param xAnwendung **Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich.  (optional)
     * @param joboe COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist.  (optional)
     * @param jobposition Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!  (optional)
     * @return OK (status code 200)
     *         or Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten. (status code 400)
     *         or Falscher oder fehlender technischer Nutzer. (status code 401)
     *         or Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten. (status code 500)
     */
    @Operation(
        operationId = "updateProcedure",
        summary = "Vorgang ändern",
        description = "Bereits befüllte Eigenschaften werden mit der übergebenen Eingabe überschrieben. Bei keiner Übergabe bleiben die bestehenden Werte erhalten. Bei jeder Änderung über die Schnittstelle wird in der eGov-Suite eine neue Version des Objekts erzeugt.",
        tags = { "/procedures" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsObjektResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DmsErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Falscher oder fehlender technischer Nutzer."),
            @ApiResponse(responseCode = "500", description = "Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.")
        },
        security = {
            @SecurityRequirement(name = "basicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ProceduresApi.PATH_UPDATE_PROCEDURE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<DmsObjektResponse> updateProcedure(
        @NotNull @Parameter(name = "userlogin", description = "**Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\\ Log-in-Name des Benutzerobjekts ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userlogin", required = true) String userlogin,
        @Parameter(name = "objaddress", description = "Objekt-ID (COO-Adresse) des Objekts", required = true, in = ParameterIn.PATH) @PathVariable("objaddress") String objaddress,
        @Parameter(name = "UpdateProcedureDTO", description = "", required = true) @Valid @RequestBody UpdateProcedureDTO updateProcedureDTO,
        @Parameter(name = "x-anwendung", description = "**Aufrufende Fachanwendung**  Für jeden Aufruf soll ersichtlich sein,  welche Fachanwendung den Aufruf getätigt hat.  Dies soll es ermöglichen, Requests und Responses den entsprechenden Fachverfahren zuzuordnen.  Für diesen Zweck wird sowohl im Request,  als auch im Response ein Parameter „businessapp“ angegeben.  Dieser Parameter ist optional und kann mit einem Namen befüllt werden.  Sofern der Aufruf einen Wert enthält, wird dieser auch im Response zurückgegeben.  Somit ist ein nachträgliches Filtern von Aufrufen möglich. ", in = ParameterIn.HEADER) @RequestHeader(value = "x-anwendung", required = false) Optional<String> xAnwendung,
        @Parameter(name = "joboe", description = "COO-Adresse der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\\ \\ Ohne Angabe der joboe und jobposition  wird die eingestellte Standardrolle und OE des Nutzers in der eAkte verwendet.\\ Wenn eine bestimmte jobposition angegeben wird, unter der dieser Aufruf ausgeführt werden soll  muss auch die entsprechende joboe des Nutzers mit angegeben werden.  Das kann z.B. notwendig sein, wenn bestimmte Funktionen nur durch Schriftgutverwalter oder Registratur ausgeführt werden dürfen.\\ Über die OE wird der Mandant zugeordnet und entsprechend die Berechtigungen geprüft.\\ Hinweis:\\ Die COO-Adresse für die joboe muss im Fachverfahren in einer Konfigurationsdatei hintelegt werden, da sie nicht per Schnittstelle ausgelesen werden kann und sich ggf. ändern kann.  Meistens ist die joboe innerhalb eines Fachbereichs für alle Benutzer gleich, so dass sie bei Änderungen einfach zu verwalten ist. ", in = ParameterIn.HEADER) @RequestHeader(value = "joboe", required = false) Optional<String> joboe,
        @Parameter(name = "jobposition", description = "Referenz der Stelle (**Rolle des Nutzers** in der eAkte). * Schriftgutverwaltung - DocumentManager * Sachbearbeitung - OfficialInCharge * Fachadministration - OpAdm * Registratur - Official * Sekretariat - Secretary * Leitung - Head * Archivar - Registrar * Vorlagenadministrator - TemplateAdministrator * Vorlagenverwaltung - TemplateManager  Es dürfen ausschließlich die o.g. genannten Stellen der LHM verwendet werden.\\ Bitte verwenden Sie die englische Bezeichnung.  Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt! ", in = ParameterIn.HEADER) @RequestHeader(value = "jobposition", required = false) Optional<String> jobposition,
        @Parameter(hidden = true) final HttpServletRequest servletRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"objname\" : \"objname\", \"objid\" : \"objid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fehlerQuelle\" : \"INTERN\", \"text\" : \"text\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
