
== Generische Suche in eAkte-REST-Schnittstelle (PoC)

=== Ziele

* Umsetzung mit Fabasoft-"Standard"-Schnittstelle (SOAP-Endpunkt der Software.Komponente FSCGOVXML)

* Umsetzung auf Basis von Spring-Boot (ohne Camel)

* Umsetzung nach dem API-First-Ansatz (mit OpenAPI-Standard für die Schnittstelle-Spezifikation)

* Abschirmung von Fabasoft-Interna (COO-Adressen, Wertebereiche für Parameter)

* "Erkundbare", selbsterklärende REST-API, alle Ressourcen über UDI/URL identifiziert und erreichbar und untereinander verlinkt

* Erweiterungen des nutzbaren Satzes von Attributen durch Konfiguration, nicht durch Software-Entwicklung ("Lifecycle Maßnahme")

* dynamischer Abruf der durch DfV definierten Attribute

=== Design-Kriterien / Best-Practices

=== Verbesserungspotential bei der REST-API-v1 ("REST-EAI")

==== Ausgewählte Punkte

===== Verben als Ressourcen/Endpunkte

===== Fabasoft COO-Addressen als Ressource-Referenzen

===== Inhomogene / inkonsistente Funktionalität
DfV-Attribute werden anders gelesen als geschrieben

=== vorläufige Design-Entscheidungen

* Deutsche Sprache für Benennung der Resourcen und der Datanaustausch-Objekte

* Attribute von Schriftgutobjekten werden einheitlich und dynamisch behandelt ("eingebaute" Attribute und Attribute aus DfV)


==== Beispiele für Such-Bedingung als Query-Parameter

===== Die Suche nach allen Akten

(Im PoC noch zusätzlich eingeschränkt auf Eigentümer = "ex.hofmann15", um exzessive Suchergebnisse zu vermeiden)

http://localhost:8080/Akten

===== Match auf eine Akte:

${/Attributbeschreibungen/lhmdfvpublic-fh_attr_auf_Formularebene}="Orangen"

http://localhost:8080/Akten?bedingungen=%24%7B%2FAttributbeschreibungen%2Flhmdfvpublic-fh_attr_auf_Formularebene%7D%3D%22Orangen%22

===== Invers (Akten die Bedingung nicht erfüllen)

${/Attributbeschreibungen/lhmdfvpublic-fh_attr_auf_Formularebene}!="Orangen"

http://localhost:8080/Akten?bedingungen=%24%7B%2FAttributbeschreibungen%2Flhmdfvpublic-fh_attr_auf_Formularebene%7D%21%3D%22Orangen%22

===== keine Akte erfüllt Bedingung:

${/Attributbeschreibungen/lhmdfvpublic-fh_attr_auf_Formularebene}="Orange"

http://localhost:8080/Akten?bedingungen=%24%7B%2FAttributbeschreibungen%2Flhmdfvpublic-fh_attr_auf_Formularebene%7D%3D%22Orange%22

