openapi: 3.0.1
info:
  title: eAkte REST-API Spezifikation
  description: Spezifikation für die REST-Schnittstelle der eAkte
  version: 2.0.0
  contact:
    name: Competence Center eAkte
    url: https://it-at-m.github.io/eakte-schnittstelle
    email: schnittstelle.eakte@muenchen.de
  license:
    name: MIT
    url: https://github.com/it-at-m/eakte-schnittstelle/blob/main/LICENSE
servers:
  - url: http://localhost:8080
security:
  - bearerAuth: []
paths:
  /api/v2/vorgaenge:
    get:
      tags:
        - Vorgang
      summary: Vorgaenge suchen
      description: |
        Mit diesem Aufruf können Vorgänge gesucht werden auf Basis von Bedingungen, die sich auf beliebige
        Attribute des Vorgangs beziehen (Standard-Metadaten der eGov-Suite oder auch Attribute aus der 
        "Definition von Verfahren").
      operationId: SucheVorgaenge
      parameters:
        - $ref: '#/components/parameters/LoginName'
        - $ref: '#/components/parameters/Rolle'
        - $ref: '#/components/parameters/Organisationseinheit'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Bedingungen'
        - $ref: '#/components/parameters/Eigenschaften'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VorgangListeResponse'
        '400':
          description: Aufruf ans DMS ist gescheitert. Im Body sind Details enthalten.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Falscher oder fehlende Anmeldeinformationen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ein unerwarteter Fehler innerhalb der EAI ist aufgetreten.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
  parameters:
    LoginName:
      name: EAkte-Login-Name
      in: header
      description: |
        **Benutzer-Login** (Benutzer-Kontext für den SOAP-Aufruf)\
        Log-in-Name des Benutzerobjekts
      required: false
      schema:
        type: string
      example: max.mustermann
    Rolle:
      name: EAkte-Rolle
      in: header
      description: |
        Referenz der Rolle (**Rolle des Nutzers** in der eAkte).
        * Sachbearbeitung - OfficialInCharge
        * Registratur - Official
        * Sekretariat - Secretary
        * Leitung - Head
        * Fachadministration - OpAdm
        * Schriftgutverwaltung - DocumentManager

        Es dürfen ausschließlich die Rollen genannt werden, 
        die bei der LHM genutzt werden.\
        Die Rolle Fachadministrator ist bei Schnittstellen nicht erlaubt!
      required: false
      schema:
        type: string
      example: DocumentManager
    Organisationseinheit:
      name: EAkte-Organisationseinheit
      in: header
      description: |
        URI der zu verwendenden **Organisationseinheit** des angemeldeten Nutzers.\
        \
        Die OE ist dann wichtig anzugeben, 
        wenn der Nutzer in mehreren OEs zugeordnet ist.\
        Über diese OE wird der Mandant zugeordnet und 
        entsprechend die Berechtigungen geprüft.
      required: false
      schema:
        type: string
      example: COO.1.2300.1.847
    Limit:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 10000
        default: 100
    Bedingungen:
      name: bedingungen
      in: query
      required: false
      schema:
        type: string
      description: |
        Bedingungen (Suchkriterien, Restriktionen) für die Suche nach Schriftgutobjekten 
        (Betreffseinheiten, Akten, Vorgänge und Dokumente)

        Die Bedingungen werden als Query-Parameter "bedingungen" als Teil der URL 
        übertragen (nach dem Fragezeichen, also "/v1/Akten?bedingungen=...").
        Dadurch können diese Suchen als einfache Strings konfiguriert bzw. im Browser als Bookmark gespeichert
        werden.

        Der Wert dieses URL-Parameters muss "URL-Encoded" sein (siehe z.B. https://en.wikipedia.org/wiki/Percent-encoding).
        Diese Kodierung wird in der Regel durch die Client-Frameworks vorgenommen. Nur wenn man z.B. über den Browser
        manuell eine URL mit Bedingung eingeben will, muss ggf. der Query-Parameter z.B. mit dem Linux-Tool "urlencode"
        umgewandelt werden.

        Die 'bedingungen' werden als WHERE-Klausel der Fabasoft-Query-Language intepretiert, mit folgenden Abweichungen:

        * Attributreferenzen werden als URI angegeben und nicht mit der Fabasoft-internen kryptischenSchreibweise. Diese URIs
        sind als Makros der Form "${...}" zu schreiben (zu klammern). Die in den geschweiften Klammern angegebenen URIs
        können unter dem Endpunkt "/Attributbeschreibungen" zusammen mit Meta-Informationen zu allen verfügbaren Attributen
        abgerufen werden. Statt ".COOSYSTEM@1.1:objowner" wird also ".${Eigentümer}" geschrieben. Man beachte den notwendigen 
        Punkt ('.') vor der Attributbenennung, was in der Fabasoft Query Language anzeigt, dass es sich um eine
        Attributbenennung im Kontext der abgefrakten Objektklasse handelt.

        * Anstelle von COO-Adressen in den WHERE-Bedingungen (z.B. ".${Eigentümer} = 'COO.2150.8800.1.230497'" kan bzw.
        soll eie andere Art von Makro benutzt werden: "#{...}". Dieses enthält in den geschweiften Klammern nicht die
        Fabasoft COO-Adresse, sondern die jedem Schnittstellen-Objekt zueigene URI, z.B. "#{/Akten/COO.1.2.3.4}". Damit 
        wird grundsätzlich nur mit "opaquen" (nicht zu interpretierenden) URIs hantiert und nicht mit Primärschlüsseln
        oder Objekt-Ids aus dem Zielsystem.
      example: |
        ${/Attributbeschreibungen/lhmdfvpublic-fh_attr_auf_Formularebene}="Orangen"
    Eigenschaften:
      name: eigenschaften
      in: query
      schema:
        type: array
        nullable: true
        items:
          type: string
  schemas:
    AnzahlListenElemente:
      type: integer
      description: |
        Anzahl der Elemente in einer Liste von Ressourcen
      example: 3
    EigenschaftEintrag:
      type: object
      required:
        - reference
        - value
      properties:
        reference:
          type: string
        value:
          type: object
    Vorgang:
      type: object
      description: |
        Repräsentation eines Vorgangs.\
        Aufgrund der Konfigurierbarkeit der Attribute (verfahrensabhängige Metadaten, siehe
        Fabasoft eGov-Suite "Definition von Verfahren") werden diese in einer dynamisch 
        aufgebauten Liste geführt und nichts als Felder in einer fixen (JSON-) Datenstruktur.
        \
        Um die innerhalb einer bestimmten Betreffseinheit verfügbaren Custom-Attribute auf
        Vorgangsebene sowie die Standard-Attribute des Vorgangs zu erfahren, kann über den Endpunkt
        '/v2/Attribute' eine Abfrage (GET-Methode) getätigt werden (s. Spezifikation dieses
        Endpunktes, in diesem Fall die Verwendung des Filters 'Schriftgutebene=Vorgang').
      required:
        - id
        - sachakteId
        - name
        - langname
        - status
        - acl
        - organisationseinheit
        - eigenschaftenMap
        - eigenschaftenListe
      properties:
        id:
          type: string
        sachakteId:
          type: string
        name:
          type: string
        langname:
          type: string
        betreff:
          type: string
        schlagworte:
          type: array
          items:
            type: string
        geschaeftsgangvermerk:
          type: string
          description: Geschäftsgangvermerk für Prozessverantwortlichen
          example: Warte auf Rückmeldung
        originalMedium:
          type: string
          enum:
            - elektronisch
            - hybrid
            - papier
        status:
          type: string
        bearbeitungsstatus:
          type: string
        acl:
          type: string
        organisationseinheit:
          type: string
        eigenschaftenMap:
          type: object
          additionalProperties: true
        eigenschaftenListe:
          type: array
          items:
            $ref: '#/components/schemas/EigenschaftEintrag'
    VorgangListeResponse:
      type: object
      properties:
        anzahl:
          $ref: '#/components/schemas/AnzahlListenElemente'
        elemente:
          type: array
          description: Liste von Vorgängen
          items:
            $ref: '#/components/schemas/Vorgang'
    ErrorResponse:
      type: object
      description: |
        Container für RFC9457 Fehlermeldung und konkrete Fabasoft Fehlermeldung falls Ursache
      required:
        - status
        - title
      properties:
        status:
          type: integer
          format: int32
        title:
          type: string
        instance:
          type: string
        detail:
          type: string
        dmsErrorReference:
          type: string
